import './globals.css'
import {Inter, Roboto} from 'next/font/google'

import { Navbar, Logo, Footer } from '@components/server';

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="container">
            <Logo/>
            <Navbar/>
            {children}
            <Footer/>
        </div>
        </body>
        </html>
    )
}
